/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex w-full min-h-[1px] max-md:max-w-full">
      {/* Add footer content here if needed */}
    </footer>
  );
}

export default Footer;
