/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-col w-full bg-zinc-100 max-md:max-w-full">
      <div className="flex flex-col w-full min-h-[727px] pb-[514px] max-md:pb-24 max-md:max-w-full">
        <div className="flex flex-col mb-0 w-full max-md:mb-2.5 max-md:max-w-full">
          <div className="flex flex-col w-full max-md:max-w-full">
            <div className="flex flex-col w-full max-md:max-w-full">
              <div className="flex flex-col justify-center py-8 w-full bg-white rounded shadow-lg max-md:max-w-full">
                <div className="flex flex-col w-full max-md:max-w-full">
                  <div className="flex relative flex-col items-center px-20 py-px w-full text-center border-t border-b border-solid bg-[linear-gradient(282deg,#F2B704_26%,#F6D060_100%)] border-y-slate-500 border-y-opacity-30 max-w-[1440px] max-md:px-5 max-md:max-w-full">
                    <div className="flex absolute inset-x-0 top-px -bottom-3.5 z-0 w-full bg-black bg-opacity-80 min-h-[68px] max-md:max-w-full" />
                    <div className="flex z-0 flex-wrap gap-8 justify-center items-center self-center px-6 py-1 w-full max-md:px-5">
                      <div className="flex flex-col grow shrink justify-center self-stretch my-auto text-base leading-relaxed text-red-900 min-w-[240px] tracking-[2px] w-[707px] max-md:max-w-full">
                        <div className="px-20 w-full max-md:px-5 max-md:max-w-full">
                          We're here to stop Trump, break MAGA, and save
                          America. Are you in?
                        </div>
                      </div>
                      <div className="flex flex-col grow shrink justify-center self-stretch my-auto text-xs tracking-wider leading-10 text-white min-w-[240px] w-[335px]">
                        <div className="flex flex-wrap items-center w-full">
                          <button className="flex overflow-hidden justify-center items-center self-stretch px-6 py-1 my-auto bg-red-900 rounded shadow-[1px_1px_5px_rgba(0,0,0,0.2)] max-md:px-5">
                            SUPPORT THE MISSION
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}

export default Header;
