/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import MainContent from "./MainContent";
import Footer from "./Footer";

function LincolnProjectPage() {
  return (
    <div className="flex flex-col bg-white">
      {/* <Header /> */}
      <MainContent />
      {/* <Footer /> */}
      <div className="flex w-full min-h-[1px] max-md:max-w-full" />
    </div>
  );
}

export default LincolnProjectPage;
