/**
 * This code was generated by Builder.io.
 */
import React from "react";

function JoinForm() {
  return (
    <form className="flex relative flex-col px-4 pt-1.5 pb-4 w-full text-center text-red-900 border border-solid shadow-sm bg-white bg-opacity-0 border-gray-600 border-opacity-20 max-md:max-w-full">
      <div className="flex absolute inset-px z-0 max-w-full bg-neutral-500 bg-opacity-10 min-h-[226px] w-[479px]" />
      <h2 className="px-20 w-full text-2xl font-light leading-[58px] max-md:px-5 max-md:max-w-full">
        JOIN THE LINCOLN PROJECT
      </h2>
      <p className="px-20 w-full text-sm leading-none max-md:px-5 max-md:max-w-full">
        Sign up to receive news and alerts via email.
      </p>
      <div className="flex z-0 flex-wrap justify-center items-center px-40 pt-8 w-full text-lg tracking-tighter leading-relaxed text-white whitespace-nowrap max-md:px-5 max-md:max-w-full">
        <button
          type="submit"
          className="flex overflow-hidden justify-center items-center self-stretch px-5 py-2 my-auto bg-red-900 rounded border-2 border-red-900 border-solid"
        >
          SUBSCRIBE
        </button>
      </div>
    </form>
  );
}

export default JoinForm;
