/**
 * This code was generated by Builder.io.
 */
import React from "react";

function JoinForm() {
  return (
    <form className="relative flex flex-col items-center px-6 py-6 w-full max-w-md mx-auto bg-white rounded-lg shadow-lg bg-opacity-80 backdrop-blur-lg max-md:max-w-full">
      {/* Background box with shadow */}
      <div className="absolute inset-0 z-0 bg-gradient-to-r from-red-500 to-red-900 opacity-20 rounded-lg shadow-md"></div>
      
      {/* Heading */}
      <h2 className="relative z-10 text-3xl font-semibold text-red-900 tracking-wide mb-2 max-md:text-2xl">
        JOIN PROJECT UNITY
      </h2>
      
      {/* Description */}
      <p className="relative z-10 text-base text-gray-700 mb-6 max-md:text-sm">
        Sign up to receive news and alerts via email.
      </p>
      
      {/* Button container */}
      <div className="relative z-10 flex justify-center w-full">
        <button
          type="submit"
          className="flex justify-center items-center px-8 py-3 bg-red-700 text-white font-bold rounded-full transition-all duration-300 ease-in-out hover:bg-red-800 hover:shadow-lg"
        >
          SUBSCRIBE
        </button>
      </div>
    </form>
  );
}


export default JoinForm;
