/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsItem from "./NewsItem";

const newsItems = [
  {
    id: 1,
    title: "Lincoln Project's Official Statement on the Presidential Debate",
    date: "September 10, 2024",
    content:
      "Lincoln Project's Official Statement on the Presidential Debate September 10, 2024 —Harris lit him up and melted his orange face paint like the Nazis in Indiana Jones. He's f*****. The Lincoln Project is a leading pro-democracy organization in the United States — dedicated to the preservation, protection, and defense of democracy. To learn more about…",
  },
  {
    id: 2,
    title: "Vice Presidents Are United: Trump Ain't It",
    date: "September 10, 2024",
    content:
      "Vice Presidents Are United: Trump Ain't It September 10, 2024 —Four years ago Mike Pence and Kamala Harris hammered at each other to get the job, but now both Vice Presidents are joined by Dick Cheney in trying to stop a destructive Trump second term. In a new ad, the Lincoln Project eviscerates Trump for…",
  },
  {
    id: 3,
    title: "Trump & RFK Jr.'s Illegal Dance",
    date: "August 30, 2024",
    content:
      "Trump & RFK Jr.'s Illegal Dance August 30, 2024 —The Lincoln Project has sent a letter today formally requesting the Department of Justice (DOJ) open an investigation into Donald Trump to determine if he violated 18 U.S.C. § 599 or 18 U.S.C. § 600 by promising to appoint, or support for appointment, RFK Jr. to…",
  },
];

function LatestNews() {
  return (
    <div className="flex flex-col px-6 py-7 mt-6 w-full shadow-sm bg-white bg-opacity-0 max-md:px-5 max-md:max-w-full">
      <h2 className="text-3xl font-light text-red-900 leading-[72px] max-md:max-w-full">
        Latest News
      </h2>
      <div className="flex flex-col mt-3.5 max-md:max-w-full">
        {newsItems.map((item) => (
          <NewsItem key={item.id} {...item} />
        ))}
      </div>
    </div>
  );
}

export default LatestNews;
