/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TwitterFeed from "./TwitterFeed";
import JoinForm from "./JoinForm";
import LatestNews from "./LatestNews";
import SearchBar from "./SearchBar";
import MissionStatement from "./MissionStatement";
import WhyWeFight from "./WhyWeFight";

function MainContent() {
  return (
    <main className="flex flex-col items-center px-20 w-full max-w-[1440px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-8 justify-center px-6 pb-6 w-full max-md:px-5">
        <TwitterFeed />
        <aside className="flex flex-col grow shrink justify-center pt-6 min-w-[240px] w-[385px] max-md:max-w-full">
          <div className="flex flex-col w-full h-[965px] max-md:max-w-full">
            <div className="flex flex-col w-full rounded-sm min-h-[800px] max-md:max-w-full">
              <JoinForm />
              <LatestNews />
              <SearchBar />
            </div>
          </div>
        </aside>
      </div>
      <MissionStatement />
      <WhyWeFight />
    </main>
  );
}

export default MainContent;
