/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MissionStatement() {
  return (
    <section className="flex relative flex-col items-center px-20 w-full text-lg leading-7 text-white max-w-[1440px] min-h-[457px] max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4aa86546a90a70ae952b499a319f150374e129f37999397df6704c725fee480f?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col justify-center px-6 py-16 w-full max-w-[1290px] max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col justify-center w-full h-[329px] max-md:max-w-full">
          <div className="flex flex-col items-start pt-1.5 w-full max-md:max-w-full">
            <h2 className="max-w-full text-3xl font-light leading-[58px] w-[500px] max-md:max-w-full">
              WE HAVE SEEN THE BEST AND WORST OF AMERICAN POLITICS
            </h2>
            <p className="mt-8 max-w-full w-[1030px] max-md:max-w-full">
              The Lincoln Project is dedicated to the preservation, protection,
              and defense of democracy. Since our launch in December 2019, The
              Lincoln Project has played a unique role in American politics. We
              entered the political arena with two stated objectives: first, to
              defeat Donald Trump at the ballot box in 2020. (Done.) The second
              was to ensure Trumpism failed alongside him. We understand that
              the real fight against Trumpism is just beginning and we're
              committed to seeing it through. <strong>Our democracy</strong>{" "}
              depends on it.
            </p>
            <p className="self-stretch mt-8 w-full max-md:max-w-full">
              Founded by former Republican strategists who understood the grave
              threat of Trumpism to our nation, the Lincoln Project team has
              expanded to include individuals from across the political
              spectrum. We are first and foremost:{" "}
              <strong>pro-democracy</strong>.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default MissionStatement;
