/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MissionStatement() {
  return (
    <section className="flex relative flex-col items-center px-20 w-[100vw] min-h-[75vh] text-lg leading-7 text-white max-w-[1440px] min-h-[457px] max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4aa86546a90a70ae952b499a319f150374e129f37999397df6704c725fee480f?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col items-center py-16 justify-center w-full max-w-[1290px] max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col justify-center w-full max-md:max-w-full">
          <div className="flex flex-col items-start pt-1.5 w-full max-md:max-w-full text-left">
            <h2 className="max-w-full text-3xl font-light leading-[58px] w-[500px] max-md:max-w-full uppercase">
            A New Era for Sri Lanka
            </h2>
            <p className="mt-8 max-w-full w-[50%] max-md:max-w-full">
            Join Sajith Premadasa in building a prosperous and fair future for all Sri Lankans. With a commitment to economic reform, sustainable growth, and empowering the common people, Sajith envisions a nation where opportunity thrives and everyone shares in its success. Together, we will create jobs, uplift communities, and ensure fairness for all—because Sri Lanka’s future belongs to its people. 
            Support the mission to make Sri Lanka stronger and more united.
            </p>
            <p className="self-stretch mt-8 w-[50%] max-md:max-w-full">
            Founded by visionaries who saw the urgent need for unity and progress, Project Unity is a movement dedicated to empowering every Sri Lankan. Inspired by Sajith Premadasa’s leadership, we’ve expanded our reach to include voices from all walks of life, united by a shared belief in democracy, equality, and opportunity. Together, we are building a prosperous future where everyone can thrive— <strong>because Sri Lanka belongs to all of us.</strong>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default MissionStatement;
