/**
 * This code was generated by Builder.io.
 */
import React from "react";

function NewsItem({ title, date, content }) {
  return (
    <article className="flex flex-col pb-5 mt-3.5 w-full max-md:max-w-full">
      <div className="flex min-h-[5em] items-center gap-[1em]">
        <div className="flex flex-col items-start p-3 mt-0 max-md:max-w-[2em] bg-[#f4f4f4] border-2 rounded-full">
          <img
            loading="lazy"
            src="/project unity icon.svg"
            alt="News item icon"
            className="object-contain aspect-square min-w-[4em] border-4 rounded-full p-1"
          />
        </div>
        <div className="flex flex-col items-start text-left">
          <h3 className="z-10 m-0 font-medium text-red-900 uppercase">
            {title}
          </h3>
          <time className="z-10 mt-0 text-sm leading-none text-red-900 max-md:px-5 max-md:mr-1.5 max-md:max-w-full">
            {date}
          </time>
        </div>
      </div>
      <p className="mt-2 text-sm leading-4 truncate text-red-900 max-md:mr-2.5 max-md:max-w-full">
        {content}
      </p>
      <div className="z-10 self-center mt-0 text-sm leading-tight text-red-900 underline">
        READ MORE
      </div>
    </article>
  );
}

export default NewsItem;
