/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TweetCard({ username, handle, content, date, image }) {
  return (
    <div className="flex flex-col p-0.5 w-full bg-white border border-solid border-neutral-200">
      <div className="flex overflow-hidden gap-6 justify-center items-start py-3.5 pr-2.5 pl-40 w-full min-h-[56px] max-md:pl-5">
        <div className="flex gap-3 items-start w-px text-xs text-neutral-700">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0754b4f8d167fca1961e005f3b001ecac3a13ccc1d2fe459b17abaf599ab66bc?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
            alt={`${username}'s profile picture`}
            className="object-contain shrink-0 rounded-2xl aspect-square w-[30px]"
          />
          <div className="flex flex-col">
            <div className="w-full font-bold leading-4">{username}</div>
            <div className="w-full leading-tight whitespace-nowrap">
              {handle}
            </div>
          </div>
        </div>
        <div className="flex flex-col w-[30px]">
          <div className="flex items-start w-[30px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/1772d38210e8cbf52ef2a37ccb9db635edc1802224abf109fff2619b01e612be?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
              alt="Twitter verified badge"
              className="object-contain aspect-square w-[30px]"
            />
          </div>
        </div>
      </div>
      <div className="flex flex-col pt-5 pr-4 pb-px pl-5 w-full">
        <div className="flex flex-col w-full text-sm leading-6">
          <div className="w-full whitespace-pre-wrap">{content}</div>
          {image && (
            <img
              loading="lazy"
              src={image}
              alt="Tweet image"
              className="object-contain aspect-[0.93] w-[191px]"
            />
          )}
        </div>
        <div className="flex flex-col pt-7 w-full">
          <div className="flex gap-2.5 items-start pb-2 w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8d09ed3768cef2af6366fd1ac42762f7fd2e536fe49f1079bce5d0b579074d3d?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
              alt="Reply icon"
              className="object-contain shrink-0 w-3.5 aspect-[1.08]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3d09a453a66a114360d6b3be93a8aff76a36fb4a801af93b8ab3777ff95c2e18?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
              alt="Retweet icon"
              className="object-contain shrink-0 aspect-[1.39] w-[18px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e120bd2d83afdb8bf8e649f3dbcb3c2ad1817d3fe23e046f150d4f1a6bb79c38?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
              alt="Like icon"
              className="object-contain shrink-0 aspect-[1.15] w-[15px]"
            />
          </div>
          <div className="flex justify-center items-start pt-0.5 pl-32 w-full text-xs font-bold leading-snug text-zinc-400 max-md:pl-5">
            <div className="flex-1 shrink w-full">{date}</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TweetCard;
