/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TweetCard from "./TweetCard";

const tweets = [
  {
    id: 1,
    username: "The Lincoln Project",
    handle: "@ProjectLincoln",
    content:
      "Well...\nx.com/ProjectLincoln…\nThe Lincoln Project\n@ProjectLincoln\nA sneak preview of the\nKamala vs. Trump debate\nhttps://t.co/lbCy6ERIRj",
    date: "11 Sep 2024",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c60c052d282c5971024839bfe6474c56df5f31a164e957f9fa0538b25bb6ead5?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc",
  },
  {
    id: 2,
    username: "The Lincoln Project",
    handle: "@ProjectLincoln",
    content:
      "Kamala Harris did exactly what she needed to do at last night's debate. She showed the American people exactly what kind of candidate Donald Trump is, says LP Chief of Staff",
    date: "11 Sep 2024",
  },
  // Add more tweet objects as needed
];

function TwitterFeed() {
  return (
    <div className="flex flex-col grow shrink items-center self-start pt-6 min-w-[240px] w-[633px] max-md:max-w-full">
      <div className="flex overflow-hidden flex-col w-full max-w-[729px] max-md:max-w-full">
        <div className="flex items-start">
          {tweets.map((tweet) => (
            <TweetCard key={tweet.id} {...tweet} />
          ))}
        </div>
      </div>
    </div>
  );
}

export default TwitterFeed;
