/**
 * This code was generated by Builder.io.
 */
import React from "react";

function WhyWeFight() {
  return (
    <section className="flex relative flex-col w-[100vw] text-lg leading-7 text-white max-w-[1440px] min-h-[696px] max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/2d3cad9824320e47f0218d9a20db168b47163995c110f88ac8944ca2e2b343c2?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col justify-center px-6 py-8 w-full max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col justify-center w-full h-[633px] max-md:max-w-full">
          <div className="flex flex-col px-16 pt-16 pb-16 w-full max-md:px-5 max-md:max-w-full">
            <h2 className="w-full text-3xl font-light leading-[58px] max-md:max-w-full">
              WHY WE FIGHT
            </h2>
            <p className="w-full text-white max-md:max-w-full">
            Sri Lanka stands at a crossroads, with many citizens struggling under the weight of economic disparity, corruption, and a political system that no longer serves the people. <strong>Project Unity</strong> is here because we recognize that this is not the future Sri Lankans deserve. The gap between the wealthy and the struggling majority grows wider, and communities that once thrived are now being left behind. Corruption and inequality are threatening the very foundations of our democracy.
            </p>
            <p className="pt-8 w-full max-md:max-w-full">
            But there is hope. At <strong>Project Unity</strong>, we believe there is a solution—a path where economic justice prevails and democracy thrives. We are fighting to create a Sri Lanka where opportunities are not reserved for the few, but accessible to all. By addressing economic disparities and empowering communities through sustainable development, we can lay the groundwork for a brighter future. We know that the people, not corrupt systems, should be at the center of our nation’s progress.
            </p>
            <p className="pt-8 w-full max-md:max-w-full">
            Our vision is clear, and our desire is strong: we seek a nation where fairness, transparency, and unity are the driving forces behind every decision. Imagine a Sri Lanka where everyone, regardless of background, can succeed and prosper. This is not just a dream—it is within reach, and together, we can make it a reality.
            </p>
            <p className="pt-8 w-full max-md:max-w-full">
            Now is the time to act. Join us in this movement for change. Together, we can build a stronger, more united Sri Lanka. <strong>Support Project Unity</strong> and be a part of this transformative journey.
            </p>
            <p className="pt-8 w-full font-bold leading-relaxed max-md:max-w-full">
              This is why we fight.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default WhyWeFight;
