/**
 * This code was generated by Builder.io.
 */
import React from "react";

function WhyWeFight() {
  return (
    <section className="flex relative flex-col w-full text-lg leading-7 text-white max-w-[1440px] min-h-[696px] max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/2d3cad9824320e47f0218d9a20db168b47163995c110f88ac8944ca2e2b343c2?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
        alt="Background image"
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col justify-center px-6 py-8 w-full max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col justify-center w-full h-[633px] max-md:max-w-full">
          <div className="flex flex-col px-16 pt-16 pb-16 w-full max-md:px-5 max-md:max-w-full">
            <h2 className="w-full text-3xl font-light leading-[58px] max-md:max-w-full">
              WHY WE FIGHT
            </h2>
            <p className="w-full text-white max-md:max-w-full">
              Our mission is to protect the American Republic from Donald Trump
              and those who identify (publicly or privately) as MAGA supporters.
              While we are optimistic about the future, we are not complacent.
              In 2020, it took an ad-hoc coalition to ensure Trump's defeat. In
              2022, we built a coalition across the political spectrum and again
              bought democracy some breathing room. We agree with Trump on only
              one thing: <strong>2024 is a battle for America's future</strong>.
            </p>
            <p className="pt-8 w-full max-md:max-w-full">
              President Abraham Lincoln led the United States through the
              bloodiest, most divisive, and most decisive period of our nation's
              history. He fought not because he wanted to, but because he knew
              the dual goals of preserving the Union and the end of slavery
              would be achieved only through armed conflict. At Gettysburg, he
              implored us not to forget those who had given "their last full
              measure of devotion" to preserving the American experiment.
            </p>
            <p className="pt-8 w-full max-md:max-w-full">
              Today, we find our nation divided again – faced with a growing
              authoritarian movement populated by millions of radicalized voters
              for whom this fight is existential as well as hyper-partisanship
              and Ultra-MAGA movements within the government itself. Donald
              Trump and those who ascribe to Trumpism are a clear and present
              danger to the Constitution and our Republic.
            </p>
            <p className="pt-8 w-full font-bold leading-relaxed max-md:max-w-full">
              This is why we fight.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default WhyWeFight;
