/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SocialIcons from "./SocialIcons";
import Logo from "./Logo";

function Footer() {
  return (
    <footer className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col items-center px-20 w-full bg-white max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col px-6 w-full max-w-[1290px] max-md:px-5 max-md:max-w-full">
          <div className="flex gap-5 justify-center py-8 w-full max-md:max-w-full">
            <FooterLinks />
            <FooterActions />
            <FooterLogo />
          </div>
        </div>
      </div>
      <FooterCopyright />
    </footer>
  );
}

function FooterLinks() {
  const links = [
    [
      {
        name: "Current Updates",
        url: "/current-updates",
      },
      {
        name: "Ads & Quick Actions",
        url: "/ads-quick-actions",
      },
      {
        name: "Podcast",
        url: "/podcast",
      },
     {
        name: "Deep Dive",
        url: "/deep-dive",
      }
    ], 
     [ {
        name: "Media",
        url: "/media",
      },
      {
        name: "Get in Touch",
        url: "/get-in-touch",
      },
      {
        name: "Home",
        url: "/",
      }
    ]
  ];

  return (
    <>
      {links.map((column, index) => (
        <div
          key={index}
          className="flex justify-center items-start py-5 h-full text-lg font-medium text-center uppercase text-rose-950 w-[236px]"
        >
          <div
            className={`flex flex-col items-center px-4 w-[236px] ${
              index === 1 ? "pb-6" : ""
            }`}
          >
            {column.map((link, linkIndex) => (
              <a href={link.url} key={linkIndex} className="whitespace-nowrap cursor-pointer">
                {link.name}
              </a>
            ))}
          </div>
        </div>
      ))}
    </>
  );
}

function FooterActions() {
  return (
    <div className="flex flex-col min-w-[240px] w-[271px]">
      <div className="flex justify-center items-center w-full">
        <div className="flex flex-col flex-1 shrink self-stretch my-auto w-full basis-0 min-w-[240px]">
          <div className="flex justify-center w-full">
            <div className="flex h-full min-w-[240px]">
              <div className="flex flex-col justify-center items-center px-6 min-w-[240px] max-md:px-5">
                <FooterAction
                  text="Contribute"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/55b22283d36fda7e9445859cd3e23c317719f8efe0be8c00b0ee907ee82c5fa5?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
                />
                <FooterAction
                  text="Join Us"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/7667dfa233fc1ac05fcd71a3da38559bc8ddfda3e7b8e8628d746ccb1a8ac933?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <SocialIcons />
    </div>
  );
}

function FooterAction({ text, icon }) {
  return (
    <div className="flex flex-col w-full h-9 max-w-[314px]">
      <div className="flex gap-1.5 items-center px-1 py-1.5 w-full">
        <div className="flex justify-center items-start self-stretch pt-px pb-0.5 my-auto w-[17px]">
          <img
            loading="lazy"
            src={icon}
            alt=""
            className="object-contain aspect-square w-[17px]"
          />
        </div>
        <div className="self-stretch my-auto text-lg leading-loose text-center text-orange-700 uppercase">
          {text}
        </div>
      </div>
    </div>
  );
}

function FooterLogo() {
  return (
    <div className="flex justify-center items-start h-full min-w-[240px] w-[473px] max-md:max-w-full">
      <div className="flex flex-col flex-1 shrink pb-5 w-full basis-0 min-w-[240px] max-md:max-w-full">
        <div className="flex flex-col px-16 w-full max-md:px-5 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://project-unity-2.s3.amazonaws.com/static/Gimhanna+Logo+V1.svg"
            alt="Footer Logo"
            className="object-contain aspect-[7.63] w-[350px]"
          />
        </div>
        <address className="px-24 mt-5 w-full text-lg leading-6 text-center text-orange-700 max-md:px-5 max-md:max-w-full">
          600 Pennsylvania Ave SE #15180 <br />
          Washington, DC 20003
        </address>
      </div>
    </div>
  );
}

function FooterCopyright() {
  return (
    <div className="flex flex-col items-center px-20 w-full text-lg text-center bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col px-6 w-full max-w-[1290px] max-md:px-5 max-md:max-w-full">
        <div className="flex flex-wrap justify-center pb-8 w-full max-md:max-w-full">
          <div className="flex grow shrink justify-center items-center h-full min-w-[240px] w-[497px] max-md:max-w-full">
            <div className="flex flex-col flex-1 shrink self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
              <div className="flex flex-col items-center px-20 w-full max-md:px-5 max-md:max-w-full">
                <div className="leading-7 text-orange-700 max-md:max-w-full">
                  PAID FOR BY PROJECT UNITY. <br />
                  Not authorized by any candidate or candidate's committee.
                </div>
                <div className="leading-relaxed whitespace-nowrap text-rose-950">
                  www.ProjectUnity.com
                </div>
              </div>
            </div>
          </div>
          <div className="flex grow shrink justify-center items-center py-3 h-full leading-relaxed min-w-[240px] w-[497px] max-md:max-w-full">
            <div className="flex flex-col flex-1 shrink justify-center self-stretch py-5 my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
              <div className="flex flex-wrap justify-center items-start pr-14 pl-12 w-full max-md:px-5 max-md:max-w-full">
                <div className="text-orange-700">
                  © 2024 Project Unity – All Rights Reserved |{" "}
                </div>
                <a href="/privacy-policy" className="underline text-rose-950">
                  Privacy Policy
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Footer;
