/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SocialIcons from "./SocialIcons";
import Logo from "./Logo";
import HeaderLinks from "./HeaderLinks";
import HeaderActions from "./HeaderActions";

function Header() {
  return (
    <header className="flex flex-col w-full max-md:max-w-full">
      <div className="flex flex-col items-center px-20 w-full max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col px-6 w-full max-w-[1290px] max-md:px-5 max-md:max-w-full">
          <div className="flex flex-wrap justify-center w-full min-h-[100px] max-md:max-w-full">
            <SocialIcons />
            <Logo />
            <HeaderActions />
          </div>
        </div>
      </div>
      <HeaderLinks />
    </header>
  );
}

export default Header;
