/**
 * This code was generated by Builder.io.
 */
import React from "react";

function HeaderActions() {
  return (
    <div className="flex grow shrink h-full min-w-[240px] w-[317px]">
      <div className="flex flex-1 shrink basis-0 h-[100px] w-[105px]" />
      <div className="flex items-center py-6 h-full min-w-[240px]">
        <div className="flex self-stretch my-auto min-w-[240px]">
          <div className="flex flex-wrap justify-center items-center h-full min-w-[240px]">
            <HeaderAction
              text="Contribute"
              icon="https://cdn.builder.io/api/v1/image/assets/TEMP/7070f84021ae9fdf4f3bc1782fa452c60528f20208a774e941f1c5d703f01e51?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
            />
            <HeaderAction
              text="Join Us"
              icon="https://cdn.builder.io/api/v1/image/assets/TEMP/0aa4c899c0cfb1a004a9b33d8977c6e159b9aa47d4236501c2d6d69c833a5015?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

function HeaderAction({ text, icon }) {
  return (
    <div className="flex flex-col self-stretch my-auto">
      <div className="flex gap-1.5 px-3.5 py-4 w-full">
        <div className="flex justify-center items-start self-start pt-0.5">
          <img
            loading="lazy"
            src={icon}
            alt=""
            className="object-contain aspect-square w-[18px]"
          />
        </div>
        <div className="grow shrink text-xs tracking-wider leading-3 uppercase text-rose-950">
          {text}
        </div>
      </div>
    </div>
  );
}

export default HeaderActions;
