/**
 * This code was generated by Builder.io.
 */
import React from "react";

const links = [
  "Latest News",
  "ADS & RAPID RESPONSE",
  "PODCAST",
  "THE BREAKDOWN",
  "PRESS",
  "SHOP GEAR",
  "Honestly Abe",
  "Leadership",
  "Contact",
  "Home",
];

function HeaderLinks() {
  return (
    <nav className="flex flex-col justify-center items-center px-20 py-px w-full text-base leading-relaxed uppercase border-t border-b border-solid border-y-slate-500 border-y-opacity-30 text-rose-950 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col justify-center py-2.5 w-full max-w-[1290px] max-md:max-w-full">
        <div className="flex justify-center px-14 w-full max-md:px-5 max-md:max-w-full">
          <div className="flex items-center h-full min-w-[240px] max-md:max-w-full">
            <div className="flex self-stretch my-auto min-w-[240px] max-md:max-w-full">
              <div className="flex flex-wrap justify-center items-center h-full min-w-[240px] max-md:max-w-full">
                {links.map((link, index) => (
                  <div
                    key={index}
                    className={`flex flex-col self-stretch my-auto ${
                      index === links.length - 1 ? "text-neutral-500" : ""
                    }`}
                  >
                    <div className="px-3 py-2.5 w-full">{link}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}

export default HeaderLinks;
