/**
 * This code was generated by Builder.io.
 */
import React from "react";

const links = [  
  {
    name: "Current Updates",
    url: "/current-updates",
  },
  {
    name: "Ads & Quick Actions",
    url: "/ads-quick-actions",
  },
  {
    name: "Podcast",
    url: "/podcast",
  },
  {
    name: "Deep Dive",
    url: "/deep-dive",
  },
  {
    name: "Media",
    url: "/media",
  },
  {
    name: "Get in Touch",
    url: "/get-in-touch",
  },
  {
    name: "Home",
    url: "/",
  }
];

function HeaderLinks() {
  return (
    <nav className="flex flex-col justify-center items-center px-20 py-px w-full text-base leading-relaxed uppercase border-t border-b border-solid border-y-slate-500 border-y-opacity-30 text-rose-950 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col justify-center py-2.5 w-full max-w-[1290px] max-md:max-w-full">
        <div className="flex justify-center px-14 w-full max-md:px-5 max-md:max-w-full">
          <div className="flex items-center h-full min-w-[240px] max-md:max-w-full">
            <div className="flex self-stretch my-auto min-w-[240px] max-md:max-w-full">
              <div className="flex flex-wrap justify-center items-center h-full min-w-[240px] max-md:max-w-full">
                {links.map((link, index) => (
                  <div
                    key={index}
                    className={`flex flex-col self-stretch cursor-pointer my-auto ${
                      window.location.pathname == link.url ? "text-neutral-500" : ""
                    }`}
                  >
                    <a href={link.url} className="px-3 py-2.5 w-full">{link.name}</a>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}

export default HeaderLinks;
