/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";
import MainContent from "./MainContent";

function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <MainContent>
        {children}
      </MainContent>
      <Footer />
    </div>
  );
}

export default Layout;
