/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <div className="flex grow shrink justify-center items-center h-full min-w-[240px] w-[371px] max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9515789627b0757f63ef45beb125fd050120f19e758fe401a64224a83ba6756?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc"
        alt="Company Logo"
        className="object-contain self-stretch my-auto aspect-[8.26] min-w-[240px] w-[428px]"
      />
    </div>
  );
}

export default Logo;
