/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MainContent({ children }) {
  return (
    <main className="flex overflow-hidden flex-col bg-white">
      { children }
    </main>
  );
}

export default MainContent;
