/**
 * This code was generated by Builder.io.
 */
import React from "react";

const socialIcons = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/5d7091148b92b4caebfa685b5392ac9be0ed11cd3d7549ac57d97615f47aff8b?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc",
    alt: "Social icon 1",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/7a4fcd7da69bdfa333c438ff284f6b48ea558731cbd14d560c7f033acd13626b?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc",
    alt: "Social icon 2",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/3cea83a46aead30c1a36cd5424a1df1377274e5c97c30d98a8294e49b48883fc?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc",
    alt: "Social icon 3",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/ce3b32bd73650faf6ad75ad7f77af11ee77d793b7a046453aca6a3b390048e67?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc",
    alt: "Social icon 4",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6e88962d5d0618ddee4fd1f014539d3fe9d8698146309e4f9536062fa0676959?placeholderIfAbsent=true&apiKey=553b31a98a6c4f6db980cd4c031d36cc",
    alt: "Social icon 5",
  },
];

function SocialIcons() {
  return (
    <div className="flex grow shrink h-full min-w-[240px] w-[317px]">
      <div className="flex flex-col justify-center pr-2.5 min-w-[208px] w-[215px]">
        <div className="flex items-center py-8 max-w-full min-h-[100px] w-[205px]">
          <div className="flex flex-col self-stretch my-auto w-[205px]">
            <div className="flex flex-wrap gap-1.5 items-center w-full">
              {socialIcons.map((icon, index) => (
                <div
                  key={index}
                  className="flex grow shrink justify-center items-center self-stretch p-2.5 my-auto rounded min-h-[36px] w-[30px]"
                >
                  <div className="flex items-start self-stretch my-auto w-[18px]">
                    <img
                      loading="lazy"
                      src={icon.src}
                      alt={icon.alt}
                      className="object-contain aspect-square w-[18px]"
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-1 shrink basis-0 h-[100px] w-[181px]" />
    </div>
  );
}

export default SocialIcons;
